Preserve data
nevisende/oob-school-library pull request #6
Opened 2022-03-08 16:52 UTC by nevisende

# Preserve data
 - We checked the documentation for Ruby's [JSON library](https://ruby-doc.org/stdlib-3.0.0/libdoc/json/rdoc/JSON.html)[](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/school_library_preserve_data.md#need-a-big-picture).
 - On exit from our app is saved all the data (books, people, and rentals) into JSON files. One per type of data we are storing and named accordingly (e.g. `rentals.json`)
- On startup of our app is loaded all data from files. Handled the case when one or more of the files are missing.

2022-03-08 17:56 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @nevisende and @AnselemOdims,

Good job so far!
✔️ Implementation of storage files
✔️ Data is stored when files are present
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
### 🛑 Check this out too 🛑 
- [x] **In your README, kindly add instructions on how to run the app in locally (`ruby main.rb`)**

- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-08 17:56 UTC, TedLivist commented on store.rb
> +      json_to_arr = read_convert('people.json')
- [ ] When I delete your `.json` storage files, I get errors (see the first image) when trying to store a created **Person**. As stated in the requirements (see the second image), your app should handle cases when the storage files are not available. Kindly ensure that a new `people.json` file is created when not available.

  **SUGGESTION:** Just after the `if` statement here, you can create a `people.json` file if it does not exist like so:
  ```
  if item.is_a?(Person)
    File.open('people.json', 'w') {|f| f.write JSON.generate([]) } unless File.exist? 'people.json'
    ....
  ```


  Your error | The requirements
  :---:|:---:
  ![anselem-people-json](https://user-images.githubusercontent.com/36542986/157293114-60581c4b-898d-49f4-9c1c-be00402870a9.jpg) | ![anselem-json-req](https://user-images.githubusercontent.com/36542986/157293109-3514f9c8-1fa8-4e42-b6d2-aa931d621eb2.jpg)

2022-03-08 17:56 UTC, TedLivist commented on store.rb
> +    JSON.parse(File.read('people.json')).map do |person|
- [ ] You should also handle the missing storage `people.json` file here if the file does not exist.

  **SUGGESTION:** After the method declaration, you can return an empty array if the file does not exist, like so: 
  ```
  def self.list_all_people
    return [] unless File.exists?('people.json')
    
    JSON.parse(File.read...
    ...
  ```
  ![anselem-people-json-2](https://user-images.githubusercontent.com/36542986/157295419-c2a31cf2-813a-49db-8172-3597dd75b73d.jpg)

2022-03-08 17:56 UTC, TedLivist commented on store.rb
> +      json_to_arr = read_convert('books.json').push({ 'title' => item.title, 'author' => item.author })
- [ ] Kindly ensure that a new `books.json` file is created when not available.

2022-03-08 17:56 UTC, TedLivist commented on store.rb
> +    JSON.parse(File.read('books.json')).map { |book| puts "Title: \"#{book['title']}\" Author: #{book['author']}" }
- [ ] Kindly ensure that the missing `books.json` file is handled when not available as well.

2022-03-08 17:56 UTC, TedLivist commented on creation.rb
>    end
- [ ] Kindly ensure that the `rentals.json` file is created when it is not available.

  ![anselem-rentals](https://user-images.githubusercontent.com/36542986/157296485-35b9ff94-2fd5-4aef-8511-dc6f28cf0f41.jpg)

2022-03-09 08:26 UTC, nevisende commented on creation.rb
>    end
Thank you for your review and suggestion :)

2022-03-09 09:12 UTC, merged